# This is a config for E2B sandbox template.
# You can use template ID (k9vtpp736t2dtww1fv8w) or template name (lov-clone) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lov-clone") # Sync sandbox
# sandbox = await AsyncSandbox.create("lov-clone") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lov-clone')

team_id = "386a3d44-d1b4-4aad-a33d-4ae6d8fc7d0a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lov-clone"
template_id = "k9vtpp736t2dtww1fv8w"
